FROM golang:1.7-alpine

RUN apk update && apk add wget git
RUN wget https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-amd64-v0.2.0.tar.gz
RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.2.0.tar.gz

RUN mkdir -p /go/src/github.com/eventials/migration
WORKDIR /go/src/github.com/eventials/migration

RUN go get -u github.com/kardianos/govendor
